"""Verilog backend: lower a :class:`~silogic.fpga.circuit.LogicNetCircuit` to a
synthesizable Verilog-2001 module.

The generated module is a feed-forward stack of LUTs:

  * Each logic node becomes a one-line combinational assignment
    ``y = (TT >> {operands}) & 1'b1`` — a constant-table indexed by the node's
    selected wires. Synthesis tools map each such expression to one LUT (arity
    <= the device LUT size, e.g. LUT6 holds arity 6), so the node count is the
    LUT count.
  * The ``GroupSum`` head becomes ``num_classes`` adder trees (block popcounts)
    exposed as the ``class_scores`` bus, plus a combinational argmax ``pred``.

Two forms:

  * ``pipeline=False`` (default) — a purely combinational module (just ``x`` ->
    ``class_scores``/``pred``). Lowest area, single-cycle, deep critical path.
  * ``pipeline=True`` — a registered pipeline: the input, every layer, and the
    head are each registered (clocked by ``clk``). Latency is ``depth + 2``
    cycles, one new result per cycle. NB: the ``GroupSum`` popcount + argmax is
    a *single* registered stage, and on these nets it is the critical path (the
    gate fabric collapses to ~2 LUT levels), so the registered form's Fmax is
    only modestly above the combinational one until the popcount is itself
    pipelined — see :func:`silogic.fpga.benchmark_fpga`, which reports the gate
    fabric vs head depths and the registered-popcount Fmax ceiling.

``tau`` is a positive scale shared by all classes, so it never changes the
argmax and is *not* applied in hardware; ``class_scores`` are the raw integer
block popcounts (divide by ``tau`` downstream if you need the actual logits).
"""
from __future__ import annotations

from typing import List

from .circuit import LogicNetCircuit, Layer, LutNode, _is_passthrough


def _hexlit(value: int, width: int) -> str:
    """A sized Verilog hex literal of ``width`` bits."""
    ndigits = (width + 3) // 4
    return f"{width}'h{value:0{ndigits}x}"


def _node_expr(prev: str, node: LutNode) -> str:
    """Combinational RHS for one node reading wires from bus ``prev``."""
    # Constant gates (False/True) and pure pass-throughs need no LUT.
    if node.is_const:
        return "1'b1" if node.tt[0] else "1'b0"
    if _is_passthrough(node):
        return f"{prev}[{node.idx[0]}]"
    arity = node.arity
    P = 1 << arity
    const = 0
    for p in range(P):
        if node.tt[p]:
            const |= 1 << p
    # address = {op_{arity-1}, ..., op_0}  (operand 0 is the LSB)
    operands = ", ".join(f"{prev}[{node.idx[j]}]" for j in range(arity - 1, -1, -1))
    if arity == 1:
        sel = f"{prev}[{node.idx[0]}]"
        return f"({_hexlit(const, P)} >> {sel}) & 1'b1"
    return f"({_hexlit(const, P)} >> {{{operands}}}) & 1'b1"


def _adder_tree(terms: List[str]) -> str:
    """A balanced ``+`` reduction (keeps expressions shallow for the tools)."""
    if len(terms) == 1:
        return terms[0]
    mid = len(terms) // 2
    return f"({_adder_tree(terms[:mid])} + {_adder_tree(terms[mid:])})"


def _argmax_block(num_classes: int, score_bits: int, pred_bits: int,
                  src=lambda g: f"score_{g}") -> List[str]:
    """Unrolled combinational argmax over ``score_0..score_{NC-1}`` -> ``pred``
    (lowest index wins ties, matching ``torch.argmax``)."""
    lines = [f"  reg [{pred_bits - 1}:0] pred_c;",
             f"  reg [{score_bits - 1}:0] best_c;",
             "  always @(*) begin",
             f"    best_c = {src(0)};",
             f"    pred_c = {pred_bits}'d0;"]
    for g in range(1, num_classes):
        lines.append(f"    if ({src(g)} > best_c) begin "
                     f"best_c = {src(g)}; pred_c = {pred_bits}'d{g}; end")
    lines.append("  end")
    return lines


def to_verilog(circuit: LogicNetCircuit, module_name: str | None = None,
               pipeline: bool = False) -> str:
    """Emit a synthesizable Verilog-2001 module for ``circuit``.

    Args:
        circuit: The discretized network (:func:`~silogic.fpga.circuit.extract_logic_net`).
        module_name: Override the module name (defaults to ``circuit.name``).
        pipeline: Register the input, every layer, and the head (adds ``clk``;
            latency ``depth + 2``). Default ``False`` (combinational).

    Returns:
        The Verilog source as a string.
    """
    name = module_name or circuit.name
    NC, SW, PW = circuit.num_classes, circuit.score_bits, circuit.pred_bits
    cls_w = NC * SW
    depth = len(circuit.layers)

    L: List[str] = []
    L.append(f"// Auto-generated by silogic.fpga — do not edit.")
    L.append(f"// {circuit.summary()}")
    L.append(f"// GroupSum tau={circuit.tau} (positive scale; not applied in HW, "
             f"argmax-invariant).")
    L.append("`default_nettype none")
    L.append("")

    ports = ["input  wire " + (f"[{circuit.in_dim - 1}:0] x")]
    if pipeline:
        ports = ["input  wire clk", "input  wire rst_n"] + ports
    ports += [f"output wire [{cls_w - 1}:0] class_scores",
              f"output wire [{PW - 1}:0] pred"]
    L.append(f"module {name} (")
    L.append(",\n".join("  " + p for p in ports))
    L.append(");")
    L.append("")

    # -- helper to emit one layer's combinational logic into bus `dst` from `src`
    def emit_layer(li: int, layer: Layer, src: str, dst: str):
        L.append(f"  // layer {li}: {layer.width} nodes")
        L.append(f"  wire [{layer.width - 1}:0] {dst};")
        for o, node in enumerate(layer.nodes):
            L.append(f"  assign {dst}[{o}] = {_node_expr(src, node)};")
        L.append("")

    if not pipeline:
        # ---- combinational ----
        src = "x"
        for li, layer in enumerate(circuit.layers):
            dst = f"l{li}"
            emit_layer(li, layer, src, dst)
            src = dst
        last = src
        # GroupSum block popcounts
        g = circuit.group_size
        L.append("  // GroupSum head: per-class block popcount")
        for c in range(NC):
            terms = [f"{last}[{c * g + i}]" for i in range(g)]
            L.append(f"  wire [{SW - 1}:0] score_{c} = {_adder_tree(terms)};")
            L.append(f"  assign class_scores[{(c + 1) * SW - 1}:{c * SW}] = score_{c};")
        L.append("")
        L += _argmax_block(NC, SW, PW)
        L.append("  assign pred = pred_c;")
        L.append("")
        L.append("endmodule")
        L.append("`default_nettype wire")
        return "\n".join(L)

    # ---- pipelined ----
    # stage 0: register the input
    L.append("  // stage 0: input register")
    L.append(f"  reg [{circuit.in_dim - 1}:0] s0;")
    L.append("  always @(posedge clk) if (!rst_n) s0 <= 0; else s0 <= x;")
    L.append("")
    src = "s0"
    for li, layer in enumerate(circuit.layers):
        comb = f"l{li}_c"
        reg = f"l{li}"
        L.append(f"  // layer {li}: {layer.width} nodes (registered)")
        L.append(f"  wire [{layer.width - 1}:0] {comb};")
        for o, node in enumerate(layer.nodes):
            L.append(f"  assign {comb}[{o}] = {_node_expr(src, node)};")
        L.append(f"  reg  [{layer.width - 1}:0] {reg};")
        L.append(f"  always @(posedge clk) if (!rst_n) {reg} <= 0; else {reg} <= {comb};")
        L.append("")
        src = reg
    last = src
    g = circuit.group_size
    L.append("  // GroupSum head: per-class block popcount (registered)")
    for c in range(NC):
        terms = [f"{last}[{c * g + i}]" for i in range(g)]
        L.append(f"  wire [{SW - 1}:0] score_c_{c} = {_adder_tree(terms)};")
        L.append(f"  reg  [{SW - 1}:0] score_{c};")
        L.append(f"  always @(posedge clk) if (!rst_n) score_{c} <= 0; "
                 f"else score_{c} <= score_c_{c};")
        L.append(f"  assign class_scores[{(c + 1) * SW - 1}:{c * SW}] = score_{c};")
    L.append("")
    # argmax is combinational off the registered scores (no extra latency)
    L += _argmax_block(NC, SW, PW)
    L.append("  assign pred = pred_c;")
    L.append(f"  // latency = {depth + 2} cycles (class_scores & pred valid together)")
    L.append("")
    L.append("endmodule")
    L.append("`default_nettype wire")
    return "\n".join(L)
